### ISSUE TITLE
Addnodes

### ISSUE THREAD

**Issue by TylerAnder** [fuscata857/lingcoin#1]
Hello, any addnodes?

**Comment by TylerAnder** [comment]
192.168.80.128  ip from the readme file, is a private ip address from your router at home.

Only a "public" ip address would be working for people to connect to the coin's network.

**Comment by fuscata857** [comment]
119.56.163.13 IS public ip adress. thank you your answer

**Comment by TylerAnder** [comment]
Thank you mate

**Comment by fuscata857** [comment]
In order for us to mine this coin sufficiently first, we must monopolize
mining for the time being. I'll make sure you mine the coin slowly enough,
but we have to play a leading role in developing this coin. Can we ask for
cooperation?

2023년 3월 4일 (토) 오전 1:32, TylerAnder ***@***.***>님이 작성:

**Comment by fuscata857** [comment]
I have absolutely no intention of selling the value of Ecoins for $1 or $2
each. Therefore, I think this coin should be kept quiet and stable so that
there is no infiltration by forces while building a higher level network.
And I think collaboration with colleagues who mine together is the most
important thing.

2023년 3월 4일 (토) 오전 5:24, 허성남 ***@***.***>님이 작성:

**Comment by fuscata857** [comment]
We need to carry out various developments to further increase the value of Ecoin, and if we can jointly invest the necessary coins, we can become more powerful.
Having built the network, I think we have to make an important decision to share the responsibility for creating this coin.

**Comment by TylerAnder** [comment]
Hello, sounds good yes.  I've been mining with my CPU only, to avoid increasing the network difficulty.

Would you like me to stop mining?
